#include "signer_feature_catalog.h"

#include <string.h>

#define SIGNER_REF_PATH(path) "upstream-wallet-reference/" path
#define SATOCHIP_PATH(path) "/home/ak/123/satochip-signer/" path

static const signer_feature_t features[] = {
    {"home",
     NULL,
     "首页",
     "扫码、连接、助记词、智能卡、设置、自检",
     "首页只留常用入口。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"boot_login",
     "settings",
     "启动与登录",
     "PIN、会话、附加口令",
     "管 PIN、会话和口令。",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_pin",
     "boot_login",
     "PIN 解锁",
     "登录入口",
     "开机先解锁。",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_passphrase",
     "boot_login",
     "密码短语",
     "BIP39 密码短语",
     "临时加入密码短语。",
     SIGNER_REF_PATH("pages/passphrase.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_encrypted_backup",
     "boot_login",
     "加密备份解锁",
     "加密备份文件",
     "解密加密备份。",
     SIGNER_REF_PATH("pages/encryption_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_clear_session",
     "boot_login",
     "清除会话",
     "安全退出",
     "清空会话后退出。",
     SIGNER_REF_PATH("wallet.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"load_mnemonic",
     "pi_mnemonic_tools",
     "加载",
     "二维码 / 文件 / 手输",
     "导入助记词。",
     SIGNER_REF_PATH("pages/mnemonic_loader.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_camera",
     "load_mnemonic",
     "扫码",
     "助记词二维码/紧凑二维码",
     "扫码导入助记词。",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_sd",
     "load_mnemonic",
     "文件",
     "从文件导入",
     "从存储卡导入。",
     SIGNER_REF_PATH("sd_card.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_manual",
     "load_mnemonic",
     "手动输入",
     "单词选择器",
     "手动输单词。",
     SIGNER_REF_PATH("pages/mnemonic_editor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_digits",
     "load_mnemonic",
     "编号",
     "0-2047/0-7FF/八进制",
     "按编号导入。",
     SIGNER_REF_PATH("pages/mnemonic_loader.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_seedkeeper_mnemonic",
     "load_mnemonic",
     "智能卡",
     "从卡导入",
     "导入助记词。",
     SIGNER_REF_PATH("smartcard/seedkeeper.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_steel_restore",
     "load_mnemonic",
     "钢板",
     "0-2047",
     "按序号恢复。",
     SIGNER_REF_PATH("pages/home_pages/secondary_mnemonic.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_punch_grid",
     "load_mnemonic",
     "点阵 / 1248",
     "恢复输入",
     "点阵板和 1248 恢复。",
     SIGNER_REF_PATH("pages/tiny_seed.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_tinyseed_restore",
     "load_punch_grid",
     "点阵板恢复",
     "点位输入",
     "独立点阵板恢复页，先选 12/24 词，再按 11 列位权逐词恢复并实时显示编号和对应单词。",
     SIGNER_REF_PATH("pages/tiny_seed.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_stackbit_restore",
     "load_punch_grid",
     "1248恢复",
     "1/2/4/8 打孔",
     "独立 1248 恢复页，支持 12/15/18/21/24 词，按每词四位数字的 1/2/4/8 打孔位置恢复助记词。",
     SIGNER_REF_PATH("pages/stack_1248.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_encrypted_kef",
     "load_mnemonic",
     "加密备份",
     "文件",
     "解密加密备份。",
     SIGNER_REF_PATH("kef.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"new_mnemonic",
     "pi_mnemonic_tools",
     "创建",
     "骰子 / 硬币 / 手动",
     "生成新助记词。",
     SIGNER_REF_PATH("pages/new_mnemonic/"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_coin_entropy",
     "new_mnemonic",
     "抛硬币",
     "0/1 输入",
     "用硬币正反面取熵。",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_camera_entropy",
     "new_mnemonic",
     "相机",
     "画面熵源",
     "用相机取熵。",
     SIGNER_REF_PATH("pages/new_mnemonic/camera_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_cards_entropy",
     "new_mnemonic",
     "扑克牌",
     "洗牌抽卡",
     "按扑克牌取熵。",
     SIGNER_REF_PATH("pages/new_mnemonic/card_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_hex_entropy",
     "new_mnemonic",
     "十六进制",
     "手动熵输入",
     "输入十六进制熵。",
     SIGNER_REF_PATH("pages/new_mnemonic/manual_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_words_select",
     "new_mnemonic",
     "手动",
     "直接编辑",
     "手动选单词。",
     SIGNER_REF_PATH("pages/mnemonic_editor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_dice_d6",
     "new_mnemonic",
     "D6",
     "D6 输入",
     "输入 1-6。",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_dice_d20",
     "new_mnemonic",
     "D20",
     "D20 输入",
     "输入 1-20。",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_seedkeeper_create_mnemonic",
     "new_mnemonic",
     "智能卡",
     "卡内真随机",
     "创建助记词。",
     SIGNER_REF_PATH("smartcard/seedkeeper.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"pi_features",
     "home",
     "功能总览",
     "全部入口",
     "按签名、助记词、连接和设备分类。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"pi_signing",
     "home",
     "签名",
     "比特币 / Web3",
     "先选来源，再扫码签名。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"signing",
     "home",
     "扫码签名",
     "先选钱包",
     "先选钱包，再选来源。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx",
     "signing",
     "OKX",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_bitget",
     "signing",
     "Bitget",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_metamask",
     "signing",
     "MetaMask",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_rabby",
     "signing",
     "Rabby",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_tokenpocket",
     "signing",
     "TokenPocket",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_imtoken",
     "signing",
     "imToken",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_btc",
     "signing",
     "BTC",
     "选来源",
     "选择来源。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx_mnemonic",
     "sign_okx",
     "助记词",
     "OKX",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx_satochip",
     "sign_okx",
     "智能卡",
     "OKX",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_bitget_mnemonic",
     "sign_bitget",
     "助记词",
     "Bitget",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_bitget_satochip",
     "sign_bitget",
     "智能卡",
     "Bitget",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_metamask_mnemonic",
     "sign_metamask",
     "助记词",
     "MetaMask",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_metamask_satochip",
     "sign_metamask",
     "智能卡",
     "MetaMask",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_rabby_mnemonic",
     "sign_rabby",
     "助记词",
     "Rabby",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_rabby_satochip",
     "sign_rabby",
     "智能卡",
     "Rabby",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_tokenpocket_mnemonic",
     "sign_tokenpocket",
     "助记词",
     "TokenPocket",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_tokenpocket_satochip",
     "sign_tokenpocket",
     "智能卡",
     "TokenPocket",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_imtoken_mnemonic",
     "sign_imtoken",
     "助记词",
     "imToken",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_imtoken_satochip",
     "sign_imtoken",
     "智能卡",
     "imToken",
     "使用 Satochip 扫码签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_btc_mnemonic",
     "sign_btc",
     "助记词",
     "BTC",
     "先选择助记词，再扫码签名。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_btc_satochip",
     "sign_btc",
     "智能卡",
     "BTC",
     "使用智能卡签名。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_mnemonic",
     "internal_sign",
     "助记词",
     "本机签名",
     "当前会话",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_satochip",
     "internal_sign",
     "智能卡",
     "Satochip",
     "Web3 签名",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"pi_mnemonic_tools",
     "home",
     "助记词",
     "创建 / 导入 / 管理",
     "助记词入口。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"pi_mnemonic_advanced",
     "pi_mnemonic_tools",
     "高级",
     "加密 / 路径 / 自检",
     "加密、路径、自检。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"pi_connect_wallet",
     "home",
     "连接钱包",
     "",
     "先选钱包，再选来源。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_web3",
     "internal_connect",
     "连接钱包",
     "",
     "统一连接入口。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_okx",
     "pi_connect_wallet",
     "OKX",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_bitget",
     "pi_connect_wallet",
     "Bitget",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_metamask",
     "pi_connect_wallet",
     "MetaMask",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_rabby",
     "pi_connect_wallet",
     "Rabby",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_tokenpocket",
     "pi_connect_wallet",
     "TokenPocket",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_imtoken",
     "pi_connect_wallet",
     "imToken",
     "选来源",
     "选择来源。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_mnemonic",
     "internal_connect",
     "助记词",
     "观察账户",
     "导出常用观察账户。",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_satochip",
     "internal_connect",
     "智能卡",
     "Satochip",
     "读卡连接",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"pi_self_check",
     "home",
     "自检",
     "系统 / 设备 / 安全",
     "看版本、PIN、屏幕、触摸和存储卡。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},

    {"wallet_home",
     "pi_connect_wallet",
     "钱包",
     "主菜单",
     "扫码、公钥、地址、备份和设置。",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"wallet_dashboard",
     "wallet_home",
     "概览",
     "主屏状态",
     "显示网络、账户、脚本类型和指纹。",
     SIGNER_REF_PATH("wallet.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_public_key",
     "wallet_home",
     "公钥",
     "扩展公钥",
     "派生、公钥二维码和文本。",
     SIGNER_REF_PATH("pages/home_pages/pub_key_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_descriptor",
     "wallet_home",
     "描述符",
     "描述符",
     "单签和多签管理。",
     SIGNER_REF_PATH("pages/home_pages/wallet_descriptor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_backup",
     "wallet_home",
     "备份",
     "助记词",
     "文字、二维码和加密备份。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"wallet_addresses",
     "wallet_home",
     "地址",
     "收款 / 找零",
     "派生、二维码和路径。",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"btc_wallet",
     "pi_connect_wallet",
     "BTC",
     "观察账户",
     "选择来源。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_mnemonic",
     "btc_wallet",
     "助记词",
     "本机会话",
     "导出 zpub 或 xpub。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_satochip",
     "btc_wallet",
     "智能卡",
     "只读观察码",
     "导出 BlueWallet 观察码。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"btc_bluewallet_zpub",
     "btc_mnemonic",
     "zpub",
     "隔离见证",
     "导出 m/84'/0'/0' 观察账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_bluewallet_xpub",
     "btc_mnemonic",
     "xpub",
     "传统账户",
     "导出 m/44'/0'/0' 观察账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_satochip_zpub",
     "btc_satochip",
     "zpub",
     "智能卡隔离",
     "导出 zpub。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"btc_satochip_xpub",
     "btc_satochip",
     "xpub",
     "智能卡传统",
     "导出 xpub。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"custom_derivation",
     "pi_mnemonic_advanced",
     "派生地址",
     "任意派生地址",
     "手动输入派生路径，查看比特币或以太坊地址，并可显示二维码。",
     SIGNER_REF_PATH("pages/home_pages/address_explorer.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"sign_psbt_qr",
     "signing",
     "扫码签名",
     "二维码导入",
     "支持交易二维码解析、交易审查、签名和二维码导出流程。",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"smartcard_tools",
     "home",
     "智能卡",
     "按卡选择",
     "选择卡类型。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_card_info",
     "smartcard_satochip_tools",
     "卡片信息",
     "概览",
     "查看卡片。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_tools",
     "smartcard_tools",
     "Satochip",
     "地址、公钥、维护",
     "管理 Satochip。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_seedkeeper_tools",
     "smartcard_tools",
     "SeedKeeper",
     "状态、助记词、高级",
     "管理 SeedKeeper。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_status_page",
     "smartcard_satochip_seedkeeper_tools",
     "状态",
     "空间",
     "查看状态。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_seedkeeper_free_space",
     "smartcard_satochip_seedkeeper_tools",
     "剩余空间",
     "可用空间",
     "查看卡内剩余空间。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_seedkeeper_list_page",
     "smartcard_satochip_seedkeeper_tools",
     "列表",
     "条目",
     "查看条目。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_advanced_tools",
     "smartcard_satochip_seedkeeper_tools",
     "高级",
     "生成、派生、重置",
     "高级操作。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_generate_masterseed",
     "smartcard_seedkeeper_advanced_tools",
     "主种子",
     "生成主种子",
     "卡内生成。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_generate_2fa_secret",
     "smartcard_seedkeeper_advanced_tools",
     "2FA",
     "生成 2FA",
     "卡内生成。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_derive_master_password",
     "smartcard_seedkeeper_advanced_tools",
     "派生密码",
     "按编号",
     "派生密码。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_reset_secret",
     "smartcard_seedkeeper_advanced_tools",
     "重置条目",
     "按编号",
     "删除条目。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_create_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "创建",
     "卡内真随机",
     "创建助记词。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_write_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "写入",
     "当前助记词",
     "写入卡。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_view_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "查看",
     "卡内助记词",
     "查看助记词。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_load_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "导入",
     "卡到内存",
     "加载助记词。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_save_password",
     "smartcard_satochip_seedkeeper_tools",
     "存密码",
     "密码条目",
     "保存密码条目。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_load_descriptor",
     "smartcard_satochip_seedkeeper_tools",
     "读描述符",
     "从卡加载",
     "读取钱包描述符。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_save_descriptor",
     "smartcard_satochip_seedkeeper_tools",
     "存描述符",
     "写入卡",
     "保存钱包描述符。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_clone",
     "smartcard_satochip_seedkeeper_tools",
     "克隆",
     "卡到卡",
     "克隆卡内条目。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_change_pin",
     "smartcard_satochip_seedkeeper_tools",
     "改PIN",
     "修改卡 PIN",
     "修改 SeedKeeper PIN。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_reset",
     "smartcard_satochip_seedkeeper_tools",
     "重置",
     "按 SID 删除",
     "重置或删除条目。",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_advanced_tools",
     "smartcard_satochip_tools",
     "高级",
     "主钥、2FA、会话",
     "更多功能。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_pubkey_tools",
     "smartcard_satochip_advanced_tools",
     "认证钥",
     "导出、导入",
     "管理公钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_export_authentikey",
     "smartcard_satochip_pubkey_tools",
     "导主钥",
     "认证主钥",
     "导出主钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"smartcard_satochip_import_ndef_authentikey",
     "smartcard_satochip_pubkey_tools",
     "写NDEF",
     "32 字节私钥",
     "写入认证主钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_import_trusted_pubkey",
     "smartcard_satochip_pubkey_tools",
     "写信任钥",
     "65 字节公钥",
     "写入信任公钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_export_trusted_pubkey",
     "smartcard_satochip_pubkey_tools",
     "导信任钥",
     "信任公钥",
     "导出信任公钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"smartcard_satochip_2fa_tools",
     "smartcard_satochip_advanced_tools",
     "2FA",
     "设置、重置",
     "管理卡内 2FA。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_set_2fa_key",
     "smartcard_satochip_2fa_tools",
     "设2FA",
     "密钥、限额",
     "设置密钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_reset_2fa_key",
     "smartcard_satochip_2fa_tools",
     "清2FA",
     "挑战响应",
     "清除密钥。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_session_tools",
     "smartcard_satochip_advanced_tools",
     "会话",
     "清除",
     "清除所有会话。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_logout_all",
     "smartcard_satochip_session_tools",
     "登出",
     "清会话",
     "清除所有会话。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_path_address",
     "smartcard_satochip_tools",
     "派生地址",
     "看地址",
     "手输路径看地址。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_pubkeys",
     "smartcard_satochip_tools",
     "BTC公钥",
     "BTC xpub/ypub/zpub",
     "按主网和测试网分组。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_zpub",
     "satochip_btc_pubkeys",
     "zpub",
     "隔离见证",
     "导出 zpub。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_xpub",
     "satochip_btc_pubkeys",
     "xpub",
     "传统账户",
     "导出 xpub。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_ypub",
     "satochip_btc_pubkeys",
     "ypub",
     "兼容账户",
     "导出 ypub。",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_tpub",
     "satochip_btc_pubkeys",
     "tpub",
     "测试网",
     "导出 tpub。",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_upub",
     "satochip_btc_pubkeys",
     "upub",
     "测试网兼容",
     "导出 upub。",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_vpub",
     "satochip_btc_pubkeys",
     "vpub",
     "测试网隔离",
     "导出 vpub。",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_psbt_file",
     "signing",
     "文件签名交易",
     "存储卡导入",
     "需要从存储卡读取交易文件，解析后进入同一套交易确认流程。",
     SIGNER_REF_PATH("pages/file_manager.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_psbt_review",
     "signing",
     "交易审查",
     "金额、地址、手续费",
     "交易审查页会显示输入输出、找零识别、手续费和确认按钮。",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_psbt_export",
     "signing",
     "签名后导出",
     "二维码/文件",
     "支持已签名交易二维码导出流程。",
     SIGNER_REF_PATH("qr.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_message",
     "signing",
     "消息签名",
     "文本消息",
     "支持消息签名解析、地址路径确认、签名和结果二维码导出流程。",
     SIGNER_REF_PATH("pages/home_pages/sign_message_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},

    {"backup_export",
     "pi_mnemonic_tools",
     "备份",
     "助记词备份",
     "单词、熵、二维码和文件。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_words",
     "backup_export",
     "序号",
     "0-2047",
     "看单词编号。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_entropy",
     "backup_export",
     "原始熵",
     "十六进制",
     "看原始熵值。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_numbers",
     "backup_export",
     "序号备份",
     "0-2047 序号",
     "附带序号提示。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_steel_punch",
     "backup_export",
     "钢板",
     "打孔",
     "按序号拆打孔位。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_stackbit",
     "backup_export",
     "1248",
     "1248",
     "按 1/2/4/8 恢复。",
     SIGNER_REF_PATH("pages/stack_1248.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_grid",
     "backup_export",
     "点阵板",
     "1-1024 / 1-11",
     "黑底彩色点阵板。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_qr",
     "backup_export",
     "二维码",
     "助记词 / 加密",
     "助记词和加密二维码。",
     SIGNER_REF_PATH("qr.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_kef",
     "backup_export",
     "加密备份",
     "文件",
     "导出加密备份。",
     SIGNER_REF_PATH("kef.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"export_public_data",
     "backup_export",
     "公开信息",
     "公钥 / 描述符",
     "导出公开信息。",
     SIGNER_REF_PATH("pages/home_pages/wallet_descriptor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"backup_printer",
     "backup_export",
     "打印备份",
     "热敏打印",
     "打印接口，默认关闭。",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_NOT_STARTED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},

    {"addresses",
     "pi_connect_wallet",
     "地址工具",
     "收款、找零、核对",
     "支持地址派生、地址核对和二维码展示页面。",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_receive",
     "addresses",
     "收款地址",
     "接收地址",
     "支持收款地址列表和二维码展示。",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_change",
     "addresses",
     "找零地址",
     "找零地址",
     "支持找零地址列表和路径显示。",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_scan_check",
     "addresses",
     "扫码核对地址",
     "地址检查",
     "支持地址和描述符扫码核对入口。",
     SIGNER_REF_PATH("pages/shared/address_checker.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_qr_view",
     "addresses",
     "地址二维码",
     "二维码展示",
     "把地址转成二维码给其他设备扫描。",
     SIGNER_REF_PATH("pages/qr_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"bip85",
     "pi_mnemonic_tools",
     "BIP85",
     "派生子助记词和密码",
     "从当前钱包派生子助记词；其他格式默认不在主入口显示。",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_mnemonic",
     "pi_mnemonic_tools",
     "派生助记词",
     "12/18/24 词",
     "从当前钱包派生 12/18/24 词子助记词。",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_password",
     "bip85",
     "派生密码",
     "应用密码",
     "从主钱包派生确定性密码。",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_entropy",
     "bip85",
     "派生熵",
     "十六进制/私钥格式",
     "导出原始熵或其他格式，需要严格隐藏和确认。",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"tools",
     "home",
     "工具",
     "二维码、文件",
     "无需加载钱包即可使用二维码、存储卡和文件浏览工具。",
     SIGNER_REF_PATH("pages/tools.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_create_qr",
     "tools",
     "生成二维码",
     "文本转二维码",
     "输入普通公开文本并生成二维码，不保存内容，不连接钱包流程。",
     SIGNER_REF_PATH("pages/qr_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"tools_qr_capture",
     "tools",
     "扫描二维码",
     "二维码分类",
     "识别普通文本和网址二维码；检测到钱包或交易类内容时只提示类型，不导入、不签名。",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_file_manager",
     "tools",
     "文件管理",
     "存储卡浏览",
     "只读浏览存储卡根目录，显示文件名、目录数量和总大小。",
     SIGNER_REF_PATH("pages/file_manager.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_flash_tools",
     "tools",
     "维护工具",
     "闪存/设置存储",
     "清除设置、备份维护和恢复操作必须经过明确确认。",
     SIGNER_REF_PATH("pages/flash_tools.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"tools_encryption",
     "tools",
     "加密工具",
     "加密/解密文件",
     "加密和备份流程。",
     SIGNER_REF_PATH("pages/encryption_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"tools_mnemonic_xor",
     "pi_mnemonic_tools",
     "助记词异或",
     "分片与恢复",
     "对当前钱包与另一组同长度助记词做异或，入口有 PIN 和敏感提示。",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_xor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"tools_secondary_mnemonic",
     "pi_mnemonic_tools",
     "助记词加密",
     "手动参数",
     "对当前助记词逐词输入加减数字，可用于二次加密或还原；不预设固定参数。",
     SIGNER_REF_PATH("pages/home_pages/secondary_mnemonic.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip39_check_tools",
     "pi_mnemonic_tools",
     "BIP39 自检",
     "单词和编号核对",
     "输入单词或 0-2047 编号互查。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"settings",
     "home",
     "设置",
     "设备 / 钱包 / 安全",
     "设备、钱包和安全。",
     SIGNER_REF_PATH("settings.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_pin",
     "settings",
     "修改PIN",
     "开机 / 超时 / 关机",
     "管 PIN 和锁定策略。",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"settings_locale",
     "settings",
     "语言",
     "中文界面",
     "翻译和格式。",
     SIGNER_REF_PATH("signer_settings.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"settings_display",
     "settings",
     "亮度",
     "屏幕与布局",
     "调字体、间距和亮度。",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_camera",
     "settings",
     "相机设置",
     "扫码参数",
     "保存曝光目标和焦点位置，相机启动时自动读取这些参数。",
     SIGNER_REF_PATH("camera.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"settings_wallet",
     "settings",
     "钱包",
     "默认项",
     "设默认网络和脚本类型。",
     SIGNER_REF_PATH("pages/wallet_settings.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"settings_security",
     "settings",
     "安全",
     "锁定和清除",
     "看锁定和错误保护。",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_printer",
     "settings",
     "打印机",
     "外部输出",
     "外部输出设置。",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},

    {"web3",
     "connect_mnemonic",
     "钱包",
     "观察账户",
     "显示 EVM 地址二维码。",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_satochip",
     "smartcard_satochip_tools",
     "连接码",
     "EVM",
     "生成连接码。",
     SATOCHIP_PATH("satochip-lib/src/main/java/org/satochip/client/SatochipCommandSet.java"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_okx_mnemonic",
     "connect_okx",
     "助记词",
     "OKX 连接码",
     "生成 OKX 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_okx_satochip",
     "connect_okx",
     "智能卡",
     "OKX 连接码",
     "用智能卡生成 OKX 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_bitget_mnemonic",
     "connect_bitget",
     "助记词",
     "Bitget 连接码",
     "生成 Bitget 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_bitget_satochip",
     "connect_bitget",
     "智能卡",
     "Bitget 连接码",
     "用智能卡生成 Bitget 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_metamask_mnemonic",
     "connect_metamask",
     "助记词",
     "MetaMask 连接码",
     "生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_metamask_satochip",
     "connect_metamask",
     "智能卡",
     "MetaMask 连接码",
     "用智能卡生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_rabby_mnemonic",
     "connect_rabby",
     "助记词",
     "Rabby 连接码",
     "生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_rabby_satochip",
     "connect_rabby",
     "智能卡",
     "Rabby 连接码",
     "用智能卡生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_tokenpocket_mnemonic",
     "connect_tokenpocket",
     "助记词",
     "TokenPocket 连接码",
     "生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_tokenpocket_satochip",
     "connect_tokenpocket",
     "智能卡",
     "TokenPocket 连接码",
     "用智能卡生成 EVM 连接码。",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_imtoken_mnemonic",
     "connect_imtoken",
     "助记词",
     "imToken 连接码",
     "生成 EVM 连接码。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_imtoken_satochip",
     "connect_imtoken",
     "智能卡",
     "imToken 连接码",
     "用智能卡生成 EVM 连接码。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_okx",
     "web3",
     "OKX",
     "连接二维码",
     "给 OKX Wallet 导出观察账户连接码，用于手机端添加只读账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_bitget",
     "web3",
     "Bitget",
     "连接二维码",
     "给 Bitget Wallet 导出观察账户连接码，用于手机端添加只读账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_metamask",
     "web3",
     "MetaMask",
     "账户二维码",
     "给 MetaMask 类钱包导出 EVM 观察账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_rabby",
     "web3",
     "Rabby",
     "账户二维码",
     "给 Rabby 导出 EVM 观察账户。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_tokenpocket",
     "web3",
     "TokenPocket",
     "账户二维码",
     "给 TokenPocket 导出 EVM 观察账户连接码。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_imtoken",
     "web3",
     "imToken",
     "账户二维码",
     "给 imToken 导出 EVM 观察账户连接码。",
     SATOCHIP_PATH("docs/连接钱包教程.zh-CN.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_address",
     "web3",
     "Keystone",
     "地址显示",
     "显示由当前钱包派生的以太坊地址和二维码。",
     SIGNER_REF_PATH("web3.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_message_sign",
     "web3",
     "Web3 消息签名",
     "个人消息签名",
     "支持 personalSign；结构化签名走确认页核对后签名。",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"web3_typed_data",
     "web3",
     "结构化数据签名",
     "结构化数据",
     "支持 EIP-712 TypedData 哈希后签名，必须核对完整内容。",
     SIGNER_REF_PATH("web3.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},

    {"device_tests",
     "pi_self_check",
     "设备检测",
     "屏幕、触摸、相机、存储",
     "检查屏幕、触摸、相机、存储卡和供电状态。",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"test_screen_touch",
     "device_tests",
     "屏幕触摸",
     "屏幕和触摸",
     "检查屏幕显示、触摸坐标和边缘点击。",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"test_camera",
     "device_tests",
     "相机检查",
     "扫码检查",
     "打开摄像头检查画面链路和普通二维码识别。",
     SIGNER_REF_PATH("camera.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"test_storage",
     "device_tests",
     "存储卡检查",
     "读写检查",
     "检测存储卡挂载、读写和文件列表。",
     SIGNER_REF_PATH("sd_card.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"test_power",
     "device_tests",
     "供电检测",
     "电源和亮度",
     "显示电源状态、亮度和外设供电检查结果。",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"smartcard_probe",
     "pi_self_check",
     "检测",
     "只读",
     "识别卡片。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_maint",
     "smartcard_satochip_tools",
     "维护",
     "PIN、标签、策略",
     "维护卡片。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"smartcard_satochip_setup_pin",
     "smartcard_satochip_maint",
     "设置PIN",
     "新卡初始化",
     "新卡或重置后先设 PIN。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_change_pin",
     "smartcard_satochip_maint",
     "改PIN",
     "当前PIN/新PIN",
     "修改 PIN。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_unblock_pin",
     "smartcard_satochip_maint",
     "解锁PIN",
     "PUK解锁",
     "解锁 PIN。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_set_label",
     "smartcard_satochip_maint",
     "改标签",
     "卡片名称",
     "修改标签。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_nfc_policy",
     "smartcard_satochip_maint",
     "NFC策略",
     "NFC开关",
     "设置开关。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_feature_policy",
     "smartcard_satochip_maint",
     "功能策略",
     "功能开关",
     "设置策略。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_reset_seed",
     "smartcard_satochip_maint",
     "重置种子",
     "清空密钥",
     "清空种子。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_reset_factory",
     "smartcard_satochip_maint",
     "出厂复位",
     "重置状态",
     "恢复出厂。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_export_cert",
     "smartcard_satochip_maint",
     "证书导出",
     "卡内证书",
     "导出证书。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_import_cert",
     "smartcard_satochip_maint",
     "证书导入",
     "写入证书",
     "导入证书。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_verify_auth",
     "smartcard_satochip_maint",
     "真伪检查",
     "认证验证",
     "核验卡片。",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"delivery_check",
     "pi_self_check",
     "钱包检测",
     "固件、硬件、安全状态",
     "检查固件、硬件和安全状态。",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"system_overview",
     "pi_self_check",
     "系统",
     "版本 / 硬件 / 安全",
     "看版本、硬件快照和安全状态。",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"security_check",
     "pi_self_check",
     "安全",
     "PIN / 锁定",
     "看 PIN 和锁定策略。",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"about",
     "settings",
     "关于",
     "系统信息",
     "看版本和硬件检测。",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
};

size_t signer_feature_count(void) {
  return sizeof(features) / sizeof(features[0]);
}

const signer_feature_t *signer_feature_at(size_t index) {
  if (index >= signer_feature_count())
    return NULL;
  return &features[index];
}

const signer_feature_t *signer_feature_find(const char *id) {
  if (!id)
    return NULL;

  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (strcmp(features[i].id, id) == 0)
      return &features[i];
  }

  return NULL;
}

size_t signer_feature_child_count(const char *parent_id) {
  if (!parent_id)
    return 0;

  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].parent_id && strcmp(features[i].parent_id, parent_id) == 0)
      count++;
  }
  return count;
}

const signer_feature_t *signer_feature_child_at(const char *parent_id,
                                            size_t child_index) {
  if (!parent_id)
    return NULL;

  size_t seen = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].parent_id && strcmp(features[i].parent_id, parent_id) == 0) {
      if (seen == child_index)
        return &features[i];
      seen++;
    }
  }
  return NULL;
}

bool signer_feature_has_children(const signer_feature_t *feature) {
  return feature && signer_feature_child_count(feature->id) > 0;
}

const char *signer_feature_status_name(signer_feature_status_t status) {
  switch (status) {
  case SIGNER_FEATURE_NOT_STARTED:
    return "保护";
  case SIGNER_FEATURE_UI_READY:
    return "可查看";
  case SIGNER_FEATURE_SERVICE_STUB:
    return "维护";
  case SIGNER_FEATURE_HARDWARE_WIRED:
    return "可用";
  case SIGNER_FEATURE_VERIFIED:
    return "可检查";
  default:
    return "未知";
  }
}

const char *signer_feature_status_detail(signer_feature_status_t status) {
  switch (status) {
  case SIGNER_FEATURE_NOT_STARTED:
    return "敏感路径默认保护，请从已开放的钱包入口进入。";
  case SIGNER_FEATURE_UI_READY:
    return "中文入口和四点三寸布局可查看。";
  case SIGNER_FEATURE_SERVICE_STUB:
    return "该路径需要专门维护，默认不进入主菜单。";
  case SIGNER_FEATURE_HARDWARE_WIRED:
    return "可从对应页面使用或检查。";
  case SIGNER_FEATURE_VERIFIED:
    return "可在当前版本里进行基础检查。";
  default:
    return "状态未知。";
  }
}

const char *signer_feature_risk_name(signer_feature_risk_t risk) {
  switch (risk) {
  case SIGNER_FEATURE_RISK_VIEW_ONLY:
    return "只读";
  case SIGNER_FEATURE_RISK_SECRET_MATERIAL:
    return "敏感";
  case SIGNER_FEATURE_RISK_SIGNING:
    return "签名";
  case SIGNER_FEATURE_RISK_EXTERNAL_IO:
    return "外设";
  case SIGNER_FEATURE_RISK_DEVICE_CONTROL:
    return "设备";
  default:
    return "未知";
  }
}

const char *signer_feature_risk_detail(signer_feature_risk_t risk) {
  switch (risk) {
  case SIGNER_FEATURE_RISK_VIEW_ONLY:
    return "只显示公开信息，风险较低。";
  case SIGNER_FEATURE_RISK_SECRET_MATERIAL:
    return "涉及助记词、派生密钥或密码，必须接完整输入、确认、回退和内存清理流程。";
  case SIGNER_FEATURE_RISK_SIGNING:
    return "涉及交易或消息签名，必须完整审查内容后才能启用。";
  case SIGNER_FEATURE_RISK_EXTERNAL_IO:
    return "涉及相机、存储卡、打印机或 USB 外设，需要单独检查硬件。";
  case SIGNER_FEATURE_RISK_DEVICE_CONTROL:
    return "涉及清除、锁定、亮度或维护操作，需要二次确认。";
  default:
    return "风险未知，默认按高风险处理。";
  }
}

size_t signer_feature_count_by_status(signer_feature_status_t status) {
  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].status == status)
      count++;
  }
  return count;
}

size_t signer_feature_action_count(void) {
  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].kind == SIGNER_FEATURE_ACTION)
      count++;
  }
  return count;
}
