#include "signer_feature_catalog.h"

#include "i18n/i18n.h"

#include <string.h>

#define SIGNER_REF_PATH(path) "upstream-wallet-reference/" path
#define SATOCHIP_PATH(path) "/home/ak/123/satochip-signer/" path

static const signer_feature_t features[] = {
    {"home",
     NULL,
     "Home",
     "Scan, connect, mnemonic, smartcard, settings, self check",
     "Home keeps only common entries.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"boot_login",
     "settings",
     "Boot and Login",
     "PIN, session, passphrase",
     "Manage PIN, sessions, and passphrases.",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_pin",
     "boot_login",
     "PIN Unlock",
     "Login entry",
     "Unlock first after boot.",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_passphrase",
     "boot_login",
     "Passphrase",
     "BIP39 passphrase",
     "Temporarily add a passphrase.",
     SIGNER_REF_PATH("pages/passphrase.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_encrypted_backup",
     "boot_login",
     "Encrypted Backup Unlock",
     "Encrypted backup file",
     "Decrypt encrypted backups.",
     SIGNER_REF_PATH("pages/encryption_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"login_clear_session",
     "boot_login",
     "Clear Session",
     "Safe exit",
     "Clear the session before exit.",
     SIGNER_REF_PATH("wallet.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"load_mnemonic",
     "pi_mnemonic_tools",
     "Load",
     "QR / file / manual",
     "Import mnemonic.",
     SIGNER_REF_PATH("pages/mnemonic_loader.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_camera",
     "load_mnemonic",
     "Scan",
     "Mnemonic QR / compact QR",
     "Scan to import a mnemonic.",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_sd",
     "load_mnemonic",
     "File",
     "Import from file",
     "Import from storage card.",
     SIGNER_REF_PATH("sd_card.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_manual",
     "load_mnemonic",
     "Manual Input",
     "Word selector",
     "Enter words manually.",
     SIGNER_REF_PATH("pages/mnemonic_editor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_digits",
     "load_mnemonic",
     "Index",
     "0-2047 / 0-7FF / octal",
     "Import by index.",
     SIGNER_REF_PATH("pages/mnemonic_loader.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_seedkeeper_mnemonic",
     "load_mnemonic",
     "Smartcard",
     "Import from card",
     "Import mnemonic.",
     SIGNER_REF_PATH("smartcard/seedkeeper.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_steel_restore",
     "load_mnemonic",
     "Steel",
     "0-2047",
     "Recover by index.",
     SIGNER_REF_PATH("pages/home_pages/secondary_mnemonic.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_punch_grid",
     "load_mnemonic",
     "Punch Grid / 1248",
     "Recovery input",
     "Punch-grid and 1248 recovery.",
     SIGNER_REF_PATH("pages/tiny_seed.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_tinyseed_restore",
     "load_punch_grid",
     "Punch Grid Recovery",
     "Dot input",
     "Standalone punch-grid recovery page. Choose 12 or 24 words, then recover each word by 11 weighted columns with live index and word display.",
     SIGNER_REF_PATH("pages/tiny_seed.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_stackbit_restore",
     "load_punch_grid",
     "1248 Recovery",
     "1/2/4/8 punches",
     "Standalone 1248 recovery page for 12/15/18/21/24 words. Recover each mnemonic word from the 1/2/4/8 punch positions of its four digits.",
     SIGNER_REF_PATH("pages/stack_1248.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"load_encrypted_kef",
     "load_mnemonic",
     "Encrypted Backup",
     "File",
     "Decrypt encrypted backups.",
     SIGNER_REF_PATH("kef.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"new_mnemonic",
     "pi_mnemonic_tools",
     "Create",
     "Dice / coin / manual",
     "Generate a new mnemonic.",
     SIGNER_REF_PATH("pages/new_mnemonic/"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_coin_entropy",
     "new_mnemonic",
     "Coin Flip",
     "0/1 input",
     "Use coin flips as entropy.",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_camera_entropy",
     "new_mnemonic",
     "Camera",
     "Image entropy source",
     "Use the camera as entropy.",
     SIGNER_REF_PATH("pages/new_mnemonic/camera_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_cards_entropy",
     "new_mnemonic",
     "Cards",
     "Shuffle and draw",
     "Use playing cards as entropy.",
     SIGNER_REF_PATH("pages/new_mnemonic/card_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_hex_entropy",
     "new_mnemonic",
     "Hex",
     "Manual entropy input",
     "Enter hexadecimal entropy.",
     SIGNER_REF_PATH("pages/new_mnemonic/manual_entropy.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_words_select",
     "new_mnemonic",
     "Manual",
     "Direct edit",
     "Select words manually.",
     SIGNER_REF_PATH("pages/mnemonic_editor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_dice_d6",
     "new_mnemonic",
     "D6",
     "D6 input",
     "Enter 1-6.",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_dice_d20",
     "new_mnemonic",
     "D20",
     "D20 input",
     "Enter 1-20.",
     SIGNER_REF_PATH("pages/new_mnemonic/dice_rolls.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"new_seedkeeper_create_mnemonic",
     "new_mnemonic",
     "Smartcard",
     "On-card true random",
     "Create a mnemonic.",
     SIGNER_REF_PATH("smartcard/seedkeeper.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"pi_features",
     "home",
     "Feature Overview",
     "All entries",
     "Grouped by signing, mnemonic, connection, and device.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"pi_signing",
     "home",
     "Signing",
     "Bitcoin / Web3",
     "Choose a source before scan signing.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"signing",
     "home",
     "Scan Sign",
     "Choose wallet first",
     "Choose a wallet, then choose a source.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx",
     "signing",
     "OKX",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_bitget",
     "signing",
     "Bitget",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_metamask",
     "signing",
     "MetaMask",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_rabby",
     "signing",
     "Rabby",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_tokenpocket",
     "signing",
     "TokenPocket",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_imtoken",
     "signing",
     "imToken",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_btc",
     "signing",
     "BTC",
     "Choose Source",
     "Choose a source.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx_mnemonic",
     "sign_okx",
     "Mnemonic",
     "OKX",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_okx_satochip",
     "sign_okx",
     "Smartcard",
     "OKX",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_bitget_mnemonic",
     "sign_bitget",
     "Mnemonic",
     "Bitget",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_bitget_satochip",
     "sign_bitget",
     "Smartcard",
     "Bitget",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_metamask_mnemonic",
     "sign_metamask",
     "Mnemonic",
     "MetaMask",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_metamask_satochip",
     "sign_metamask",
     "Smartcard",
     "MetaMask",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_rabby_mnemonic",
     "sign_rabby",
     "Mnemonic",
     "Rabby",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_rabby_satochip",
     "sign_rabby",
     "Smartcard",
     "Rabby",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_tokenpocket_mnemonic",
     "sign_tokenpocket",
     "Mnemonic",
     "TokenPocket",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_tokenpocket_satochip",
     "sign_tokenpocket",
     "Smartcard",
     "TokenPocket",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_imtoken_mnemonic",
     "sign_imtoken",
     "Mnemonic",
     "imToken",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_imtoken_satochip",
     "sign_imtoken",
     "Smartcard",
     "imToken",
     "Use Satochip for scan signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_btc_mnemonic",
     "sign_btc",
     "Mnemonic",
     "BTC",
     "Select the mnemonic before scan signing.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_btc_satochip",
     "sign_btc",
     "Smartcard",
     "BTC",
     "Use the smartcard for signing.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_mnemonic",
     "internal_sign",
     "Mnemonic",
     "Local signing",
     "Current session",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_satochip",
     "internal_sign",
     "Smartcard",
     "Satochip",
     "Web3 signing",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"pi_mnemonic_tools",
     "home",
     "Mnemonic",
     "Create / import / manage",
     "Mnemonic entry.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"pi_mnemonic_advanced",
     "pi_mnemonic_tools",
     "Advanced",
     "Encryption / paths / self check",
     "Encryption, paths, and self checks.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"pi_connect_wallet",
     "home",
     "Connect Wallet",
     "",
     "Choose a wallet, then choose a source.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_web3",
     "internal_connect",
     "Connect Wallet",
     "",
     "Unified connection entry.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_okx",
     "pi_connect_wallet",
     "OKX",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_bitget",
     "pi_connect_wallet",
     "Bitget",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_metamask",
     "pi_connect_wallet",
     "MetaMask",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_rabby",
     "pi_connect_wallet",
     "Rabby",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_tokenpocket",
     "pi_connect_wallet",
     "TokenPocket",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_imtoken",
     "pi_connect_wallet",
     "imToken",
     "Choose Source",
     "Choose a source.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_mnemonic",
     "internal_connect",
     "Mnemonic",
     "Watch-only Account",
     "Export common watch-only accounts.",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"connect_satochip",
     "internal_connect",
     "Smartcard",
     "Satochip",
     "Read-card connection",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"pi_self_check",
     "home",
     "Self Check",
     "System / device / security",
     "View version, PIN, screen, touch, and storage card.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},

    {"wallet_home",
     "pi_connect_wallet",
     "Wallet",
     "Main menu",
     "Scan, public keys, addresses, backup, and settings.",
     SIGNER_REF_PATH("pages/home_pages/home.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"wallet_dashboard",
     "wallet_home",
     "Overview",
     "Home status",
     "Show network, account, script type, and fingerprint.",
     SIGNER_REF_PATH("wallet.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_public_key",
     "wallet_home",
     "Public Key",
     "Extended public key",
     "Derivation, public-key QR, and text.",
     SIGNER_REF_PATH("pages/home_pages/pub_key_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_descriptor",
     "wallet_home",
     "Descriptor",
     "Descriptor",
     "Single-sig and multisig management.",
     SIGNER_REF_PATH("pages/home_pages/wallet_descriptor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"wallet_backup",
     "wallet_home",
     "Backup",
     "Mnemonic",
     "Words, QR, and encrypted backup.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"wallet_addresses",
     "wallet_home",
     "Address",
     "Receive / change",
     "Derivation, QR, and paths.",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"btc_wallet",
     "pi_connect_wallet",
     "BTC",
     "Watch-only Account",
     "Choose a source.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_mnemonic",
     "btc_wallet",
     "Mnemonic",
     "Local session",
     "Export zpub or xpub.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_satochip",
     "btc_wallet",
     "Smartcard",
     "Read-only watch code",
     "Export BlueWallet watch-only code.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"btc_bluewallet_zpub",
     "btc_mnemonic",
     "zpub",
     "SegWit",
     "Export the m/84'/0'/0' watch-only account.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_bluewallet_xpub",
     "btc_mnemonic",
     "xpub",
     "Legacy Account",
     "Export the m/44'/0'/0' watch-only account.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"btc_satochip_zpub",
     "btc_wallet",
     "zpub",
     "Smartcard SegWit",
     "Export zpub.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"btc_satochip_xpub",
     "btc_wallet",
     "xpub",
     "Smartcard Legacy",
     "Export xpub.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"custom_derivation",
     "pi_mnemonic_advanced",
     "Derived Address",
     "Any derived address",
     "Enter a derivation path to view a Bitcoin or Ethereum address and show a QR code.",
     SIGNER_REF_PATH("pages/home_pages/address_explorer.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"sign_psbt_qr",
     "signing",
     "Scan Sign",
     "QR import",
     "Supports transaction QR parsing, review, signing, and QR export.",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"smartcard_tools",
     "home",
     "Smartcard",
     "Choose by card",
     "Choose card type.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_card_info",
     "smartcard_satochip_tools",
     "Card Info",
     "Overview",
     "View card.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_tools",
     "smartcard_tools",
     "Satochip",
     "Address, public key, maintenance",
     "Manage Satochip.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_seedkeeper_tools",
     "smartcard_tools",
     "SeedKeeper",
     "Status, mnemonic, advanced",
     "Manage SeedKeeper.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_status_page",
     "smartcard_satochip_seedkeeper_tools",
     "Status",
     "Space",
     "View status.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_seedkeeper_free_space",
     "smartcard_satochip_seedkeeper_tools",
     "Free Space",
     "Available space",
     "View remaining card space.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_seedkeeper_list_page",
     "smartcard_satochip_seedkeeper_tools",
     "List",
     "Entries",
     "View entries.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_advanced_tools",
     "smartcard_satochip_seedkeeper_tools",
     "Advanced",
     "Generate, derive, reset",
     "Advanced operations.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_generate_masterseed",
     "smartcard_seedkeeper_advanced_tools",
     "Master Seed",
     "Generate master seed",
     "Generate on card.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_generate_2fa_secret",
     "smartcard_seedkeeper_advanced_tools",
     "2FA",
     "Generate 2FA",
     "Generate on card.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_derive_master_password",
     "smartcard_seedkeeper_advanced_tools",
     "Derive Password",
     "By SID",
     "Derive password.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_reset_secret",
     "smartcard_seedkeeper_advanced_tools",
     "Delete Item",
     "Delete by SID",
     "Delete entry.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_create_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "Create",
     "On-card true random",
     "Create a mnemonic.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_write_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "Write",
     "Current mnemonic",
     "Write to card.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_view_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "View",
     "On-card mnemonic",
     "View mnemonic.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_load_mnemonic",
     "smartcard_satochip_seedkeeper_tools",
     "Import",
     "Card to memory",
     "Load mnemonic.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_load_descriptor",
     "smartcard_satochip_seedkeeper_tools",
     "Read Descriptor",
     "Load from card",
     "Read wallet descriptor.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_save_descriptor",
     "smartcard_satochip_seedkeeper_tools",
     "Save Descriptor",
     "Write to card",
     "Save wallet descriptor.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_clone",
     "smartcard_satochip_seedkeeper_tools",
     "Clone",
     "Card to card",
     "Clone on-card entries.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_change_pin",
     "smartcard_satochip_seedkeeper_tools",
     "Change PIN",
     "Change card PIN",
     "Change SeedKeeper PIN.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_seedkeeper_reset",
     "smartcard_satochip_seedkeeper_tools",
     "Wipe SeedKeeper",
     "Blank card",
     "Wipe SeedKeeper and return it to an uninitialized state.",
     "main/pages/signer_shell/signer_shell.c",
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_advanced_tools",
     "smartcard_satochip_tools",
     "Advanced",
     "Master key, 2FA, session",
     "More features.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_pubkey_tools",
     "smartcard_satochip_advanced_tools",
     "Authentikey",
     "Export, import",
     "Manage public keys.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_export_authentikey",
     "smartcard_satochip_pubkey_tools",
     "Export Main Key",
     "Authentikey master key",
     "Export master key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"smartcard_satochip_import_ndef_authentikey",
     "smartcard_satochip_pubkey_tools",
     "Write NDEF",
     "32-byte private key",
     "Write authentikey master key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_import_trusted_pubkey",
     "smartcard_satochip_pubkey_tools",
     "Write Trusted Key",
     "65-byte public key",
     "Write trusted public key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_export_trusted_pubkey",
     "smartcard_satochip_pubkey_tools",
     "Export Trusted Key",
     "Trusted public key",
     "Export trusted public key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"smartcard_satochip_2fa_tools",
     "smartcard_satochip_advanced_tools",
     "2FA",
     "Set, reset",
     "Manage on-card 2FA.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_set_2fa_key",
     "smartcard_satochip_2fa_tools",
     "Set 2FA",
     "Key, limit",
     "Set key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_reset_2fa_key",
     "smartcard_satochip_2fa_tools",
     "Clear 2FA",
     "Challenge response",
     "Clear key.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"smartcard_satochip_session_tools",
     "smartcard_satochip_advanced_tools",
     "Session",
     "Clear",
     "Clear all sessions.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_logout_all",
     "smartcard_satochip_session_tools",
     "Logout",
     "Clear session",
     "Clear all sessions.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_path_address",
     "smartcard_satochip_tools",
     "Derived Address",
     "View address",
     "Enter a path to view an address.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"connect_wallet_satochip_address",
     "pi_connect_wallet",
     "Derived Address",
     "View address",
     "Enter a path to view an address.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_pubkeys",
     "smartcard_satochip_tools",
     "BTC Public Key",
     "BTC xpub/ypub/zpub",
     "Grouped by mainnet and testnet.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_zpub",
     "satochip_btc_pubkeys",
     "zpub",
     "SegWit",
     "Export zpub.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_xpub",
     "satochip_btc_pubkeys",
     "xpub",
     "Legacy Account",
     "Export xpub.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_ypub",
     "satochip_btc_pubkeys",
     "ypub",
     "Compatible Account",
     "Export ypub.",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_tpub",
     "satochip_btc_pubkeys",
     "tpub",
     "Testnet",
     "Export tpub.",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_upub",
     "satochip_btc_pubkeys",
     "upub",
     "Testnet Compatible",
     "Export upub.",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_btc_vpub",
     "satochip_btc_pubkeys",
     "vpub",
     "Testnet SegWit",
     "Export vpub.",
     SATOCHIP_PATH("pi-signer-py/bin/pi-signer"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"sign_psbt_file",
     "signing",
     "File-signed Transaction",
     "Storage card import",
     "Reads a transaction file from the storage card, then enters the same review flow.",
     SIGNER_REF_PATH("pages/file_manager.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_psbt_review",
     "signing",
     "Transaction Review",
     "Amount, address, fee",
     "The review page shows inputs, outputs, change detection, fees, and confirmation.",
     SIGNER_REF_PATH("psbt.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_psbt_export",
     "signing",
     "Export After Signing",
     "QR / file",
     "Supports signed transaction QR export.",
     SIGNER_REF_PATH("qr.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"sign_message",
     "signing",
     "Message Signing",
     "Text message",
     "Supports message-signing parsing, address path confirmation, signing, and result QR export.",
     SIGNER_REF_PATH("pages/home_pages/sign_message_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},

    {"backup_export",
     "pi_mnemonic_tools",
     "Backup",
     "Mnemonic Backup",
     "Words, entropy, QR, and file.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_words",
     "backup_export",
     "Index",
     "0-2047",
     "View word indexes.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_entropy",
     "backup_export",
     "Raw Entropy",
     "Hex",
     "View raw entropy.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_numbers",
     "backup_export",
     "Index Backup",
     "0-2047 indexes",
     "Includes index hints.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_steel_punch",
     "backup_export",
     "Steel",
     "Punch",
     "Split indexes into punch positions.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_stackbit",
     "backup_export",
     "1248",
     "1248",
     "Recover using 1/2/4/8.",
     SIGNER_REF_PATH("pages/stack_1248.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_grid",
     "backup_export",
     "Punch Grid",
     "1-1024 / 1-11",
     "Colored punch grid on a black background.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_punch_numbers",
     "backup_export",
     "Punch Numbers",
     "1 2 4 8",
     "Show each word's punch weights as numbers.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_backup.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_seed_qr",
     "backup_export",
     "QR Code",
     "Mnemonic / encrypted",
     "Mnemonic and encrypted QR codes.",
     SIGNER_REF_PATH("qr.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"backup_kef",
     "backup_export",
     "Encrypted Backup",
     "File",
     "Export encrypted backup.",
     SIGNER_REF_PATH("kef.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"export_public_data",
     "backup_export",
     "Public Info",
     "Public key / descriptor",
     "Export public information.",
     SIGNER_REF_PATH("pages/home_pages/wallet_descriptor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"backup_printer",
     "backup_export",
     "Print Backup",
     "Thermal print",
     "Printer interface, disabled by default.",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_NOT_STARTED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},

    {"addresses",
     "pi_connect_wallet",
     "Address Tools",
     "Receive, change, verify",
     "Supports address derivation, address verification, and QR display.",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_receive",
     "addresses",
     "Receive Address",
     "Receiving address",
     "Supports receive address lists and QR display.",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_change",
     "addresses",
     "Change Address",
     "Change Address",
     "Supports change address lists and path display.",
     SIGNER_REF_PATH("pages/home_pages/addresses.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_scan_check",
     "addresses",
     "Scan to Verify Address",
     "Address check",
     "Supports scan-based address and descriptor verification.",
     SIGNER_REF_PATH("pages/shared/address_checker.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"addr_qr_view",
     "addresses",
     "Address QR",
     "QR display",
     "Convert the address into a QR code for another device to scan.",
     SIGNER_REF_PATH("pages/qr_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"bip85",
     "pi_mnemonic_tools",
     "BIP85",
     "Derive Child Mnemonics and Passwords",
     "Derive child mnemonics from the current wallet; other formats are hidden from the main entry by default.",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_mnemonic",
     "pi_mnemonic_tools",
     "Derive Mnemonic",
     "12/18/24 words",
     "Derive 12/18/24-word child mnemonics from the current wallet.",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_password",
     "bip85",
     "Derive Password",
     "App password",
     "Derive a deterministic password from the main wallet.",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip85_entropy",
     "bip85",
     "Derive Entropy",
     "Hex / private-key format",
     "Export raw entropy or other formats with strict hiding and confirmation.",
     SIGNER_REF_PATH("pages/home_pages/bip85.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"tools",
     "home",
     "Tools",
     "QR, files",
     "Use QR, storage card, and file browsing tools without loading a wallet.",
     SIGNER_REF_PATH("pages/tools.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_create_qr",
     "tools",
     "Create QR Code",
     "Text to QR",
     "Enter public text and generate a QR code without saving it or entering wallet flows.",
     SIGNER_REF_PATH("pages/qr_view.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"tools_qr_capture",
     "tools",
     "Scan QR Code",
     "QR classification",
     "Recognize plain text and URL QRs. Wallet or transaction content is identified only, not imported or signed.",
     SIGNER_REF_PATH("pages/qr_capture.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_file_manager",
     "tools",
     "File Manager",
     "Storage card browsing",
     "Browse the storage card root read-only and show file names, directory count, and total size.",
     SIGNER_REF_PATH("pages/file_manager.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"tools_flash_tools",
     "tools",
     "Maintenance Tools",
     "Flash / settings storage",
     "Clearing settings, backup maintenance, and recovery operations require explicit confirmation.",
     SIGNER_REF_PATH("pages/flash_tools.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"tools_encryption",
     "tools",
     "Encryption Tools",
     "Encrypt / decrypt files",
     "Encryption and backup flows.",
     SIGNER_REF_PATH("pages/encryption_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"tools_mnemonic_xor",
     "pi_mnemonic_tools",
     "Mnemonic XOR",
     "Shares and recovery",
     "XOR the current wallet with another mnemonic of the same length; entry includes PIN and sensitive warnings.",
     SIGNER_REF_PATH("pages/home_pages/mnemonic_xor.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"tools_secondary_mnemonic",
     "pi_mnemonic_tools",
     "Mnemonic Encryption",
     "Manual parameters",
     "Enter per-word add/subtract numbers for the current mnemonic, usable for secondary encryption or restore; no fixed parameters are preset.",
     SIGNER_REF_PATH("pages/home_pages/secondary_mnemonic.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"bip39_check_tools",
     "pi_mnemonic_tools",
     "BIP39 Self Check",
     "Word and index lookup",
     "Look up words or 0-2047 indexes in either direction.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"settings",
     "home",
     "Settings",
     "Device / wallet / security",
     "Device, wallet, and security.",
     SIGNER_REF_PATH("settings.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_pin",
     "settings",
     "Change PIN",
     "Boot / timeout / power off",
     "Manage PIN and lock policy.",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"settings_locale",
     "settings",
     "Language",
     "UI language",
     "Choose the interface language.",
     SIGNER_REF_PATH("signer_settings.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"settings_display",
     "settings",
     "Brightness",
     "Screen and layout",
     "Adjust fonts, spacing, and brightness.",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_camera",
     "settings",
     "Camera Settings",
     "Scan parameters",
     "Save exposure target and focus position; the camera loads them automatically on start.",
     SIGNER_REF_PATH("camera.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"settings_wallet",
     "settings",
     "Wallet",
     "Defaults",
     "Set default network and script type.",
     SIGNER_REF_PATH("pages/wallet_settings.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"settings_security",
     "settings",
     "Security",
     "Locking and clearing",
     "View lock and error protection.",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"settings_printer",
     "settings",
     "Printer",
     "External output",
     "External output settings.",
     SIGNER_REF_PATH("pages/settings_page.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_UI_READY,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},

    {"web3",
     "connect_mnemonic",
     "Wallet",
     "Watch-only Account",
     "Show EVM address QR code.",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_satochip",
     "smartcard_satochip_tools",
     "Connection Code",
     "EVM",
     "Generate connection code.",
     SATOCHIP_PATH("satochip-lib/src/main/java/org/satochip/client/SatochipCommandSet.java"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_okx_mnemonic",
     "connect_okx",
     "Mnemonic",
     "OKX Connection Code",
     "Generate OKX connection code.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_okx_satochip",
     "connect_okx",
     "Smartcard",
     "OKX Connection Code",
     "Generate OKX connection code with a smartcard.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_bitget_mnemonic",
     "connect_bitget",
     "Mnemonic",
     "Bitget Connection Code",
     "Generate Bitget connection code.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_bitget_satochip",
     "connect_bitget",
     "Smartcard",
     "Bitget Connection Code",
     "Generate Bitget connection code with a smartcard.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_metamask_mnemonic",
     "connect_metamask",
     "Mnemonic",
     "MetaMask Connection Code",
     "Generate EVM connection code.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_metamask_satochip",
     "connect_metamask",
     "Smartcard",
     "MetaMask Connection Code",
     "Generate EVM connection code with a smartcard.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_rabby_mnemonic",
     "connect_rabby",
     "Mnemonic",
     "Rabby Connection Code",
     "Generate EVM connection code.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_rabby_satochip",
     "connect_rabby",
     "Smartcard",
     "Rabby Connection Code",
     "Generate EVM connection code with a smartcard.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_tokenpocket_mnemonic",
     "connect_tokenpocket",
     "Mnemonic",
     "TokenPocket Connection Code",
     "Generate EVM connection code.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_tokenpocket_satochip",
     "connect_tokenpocket",
     "Smartcard",
     "TokenPocket Connection Code",
     "Generate EVM connection code with a smartcard.",
     SATOCHIP_PATH("seedsigner-os/opt/rootfs-overlay/opt/src/seedsigner/views/tp_views.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_imtoken_mnemonic",
     "connect_imtoken",
     "Mnemonic",
     "imToken Connection Code",
     "Generate EVM connection code.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_imtoken_satochip",
     "connect_imtoken",
     "Smartcard",
     "imToken Connection Code",
     "Generate EVM connection code with a smartcard.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"web3_okx",
     "web3",
     "OKX",
     "Connection QR",
     "Export an OKX Wallet watch-only connection code for adding a read-only account on mobile.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_bitget",
     "web3",
     "Bitget",
     "Connection QR",
     "Export a Bitget Wallet watch-only connection code for adding a read-only account on mobile.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_metamask",
     "web3",
     "MetaMask",
     "Account QR",
     "Export an EVM watch-only account for MetaMask-style wallets.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_rabby",
     "web3",
     "Rabby",
     "Account QR",
     "Export an EVM watch-only account for Rabby.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_tokenpocket",
     "web3",
     "TokenPocket",
     "Account QR",
     "Export an EVM watch-only connection code for TokenPocket.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_imtoken",
     "web3",
     "imToken",
     "Account QR",
     "Export an EVM watch-only connection code for imToken.",
     SATOCHIP_PATH("docs/connect-wallet-guide.md"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_address",
     "web3",
     "Keystone",
     "Address Display",
     "Show the Ethereum address and QR code derived from the current wallet.",
     SIGNER_REF_PATH("web3.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},
    {"web3_message_sign",
     "web3",
     "Web3 Message Signing",
     "Personal message signing",
     "Supports personalSign; structured signing goes through a review page before signing.",
     SIGNER_REF_PATH("pages/home_pages/web3_ui.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},
    {"web3_typed_data",
     "web3",
     "Structured Data Signing",
     "Structured data",
     "Supports EIP-712 TypedData hash signing; full content must be reviewed.",
     SIGNER_REF_PATH("web3.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SIGNING},

    {"device_tests",
     "pi_self_check",
     "Device Tests",
     "Screen, touch, camera, storage",
     "Check screen, touch, camera, storage card, and power status.",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"test_screen_touch",
     "device_tests",
     "Screen Touch",
     "Screen and touch",
     "Check display output, touch coordinates, and edge taps.",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"test_camera",
     "device_tests",
     "Camera Check",
     "Scan check",
     "Open the camera to check the image pipeline and plain QR recognition.",
     SIGNER_REF_PATH("camera.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"test_storage",
     "device_tests",
     "Storage Card Check",
     "Read/write check",
     "Check storage card mount, read/write, and file list.",
     SIGNER_REF_PATH("sd_card.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"test_power",
     "device_tests",
     "Power Check",
     "Power and brightness",
     "Show power status, brightness, and peripheral power check results.",
     SIGNER_REF_PATH("pages/device_tests.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"smartcard_probe",
     "pi_self_check",
     "Detect",
     "View Only",
     "Identify card.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"smartcard_satochip_maint",
     "smartcard_satochip_tools",
     "Maintenance",
     "PIN, label, policy",
     "Maintain card.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"smartcard_satochip_setup_pin",
     "smartcard_satochip_maint",
     "Set PIN",
     "New card setup",
     "Set a PIN first on a new or reset card.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_change_pin",
     "smartcard_satochip_maint",
     "Change PIN",
     "Current PIN / new PIN",
     "Change PIN.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_unblock_pin",
     "smartcard_satochip_maint",
     "Unlock PIN",
     "PUK unlock",
     "Unlock PIN.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_set_label",
     "smartcard_satochip_maint",
     "Change Label",
     "Card name",
     "Change label.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_nfc_policy",
     "smartcard_satochip_maint",
     "NFC Policy",
     "NFC access",
     "Set switch.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_feature_policy",
     "smartcard_satochip_maint",
     "Feature Policy",
     "Per-feature access",
     "Set policy.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_reset_seed",
     "smartcard_satochip_maint",
     "Reset Seed",
     "Clear keys",
     "Clear seed.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},
    {"satochip_reset_factory",
     "smartcard_satochip_maint",
     "Factory Reset",
     "Reset state",
     "Factory reset.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"satochip_export_cert",
     "smartcard_satochip_maint",
     "Export Certificate",
     "On-card certificate",
     "Export certificate.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_import_cert",
     "smartcard_satochip_maint",
     "Import Certificate",
     "Write certificate",
     "Import certificate.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"satochip_verify_auth",
     "smartcard_satochip_maint",
     "Authenticity Check",
     "Certificate verification",
     "Verify card.",
     SATOCHIP_PATH("pi-signer-py/vendor/pysatochip/CardConnector.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_SERVICE_STUB,
     SIGNER_FEATURE_RISK_EXTERNAL_IO},
    {"delivery_check",
     "pi_self_check",
     "Wallet Check",
     "Firmware, hardware, security status",
     "Check firmware, hardware, and security status.",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_VIEW_ONLY},

    {"system_overview",
     "pi_self_check",
     "System",
     "Version / hardware / security",
     "View version, hardware snapshot, and security status.",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
    {"security_check",
     "pi_self_check",
     "Security",
     "PIN / lock",
     "View PIN and lock policy.",
     SIGNER_REF_PATH("pages/login.py"),
     SIGNER_FEATURE_ACTION,
     SIGNER_FEATURE_HARDWARE_WIRED,
     SIGNER_FEATURE_RISK_SECRET_MATERIAL},

    {"about",
     "settings",
     "About",
     "System info",
     "View version and hardware checks.",
     SIGNER_REF_PATH("VERSION"),
     SIGNER_FEATURE_GROUP,
     SIGNER_FEATURE_VERIFIED,
     SIGNER_FEATURE_RISK_DEVICE_CONTROL},
};

size_t signer_feature_count(void) {
  return sizeof(features) / sizeof(features[0]);
}

const signer_feature_t *signer_feature_at(size_t index) {
  if (index >= signer_feature_count())
    return NULL;
  return &features[index];
}

const signer_feature_t *signer_feature_find(const char *id) {
  if (!id)
    return NULL;

  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (strcmp(features[i].id, id) == 0)
      return &features[i];
  }

  return NULL;
}

size_t signer_feature_child_count(const char *parent_id) {
  if (!parent_id)
    return 0;

  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].parent_id && strcmp(features[i].parent_id, parent_id) == 0)
      count++;
  }
  return count;
}

const signer_feature_t *signer_feature_child_at(const char *parent_id,
                                            size_t child_index) {
  if (!parent_id)
    return NULL;

  size_t seen = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].parent_id && strcmp(features[i].parent_id, parent_id) == 0) {
      if (seen == child_index)
        return &features[i];
      seen++;
    }
  }
  return NULL;
}

bool signer_feature_has_children(const signer_feature_t *feature) {
  return feature && signer_feature_child_count(feature->id) > 0;
}

const char *signer_feature_status_name(signer_feature_status_t status) {
  switch (status) {
  case SIGNER_FEATURE_NOT_STARTED:
    return i18n_tr_or("feature.status.protected", "Protected");
  case SIGNER_FEATURE_UI_READY:
    return i18n_tr_or("feature.status.visible", "Visible");
  case SIGNER_FEATURE_SERVICE_STUB:
    return i18n_tr_or("feature.status.maintenance", "Maintenance");
  case SIGNER_FEATURE_HARDWARE_WIRED:
    return i18n_tr_or("feature.status.available", "Available");
  case SIGNER_FEATURE_VERIFIED:
    return i18n_tr_or("feature.status.checkable", "Checkable");
  default:
    return i18n_tr_or("feature.status.unknown", "Unknown");
  }
}

const char *signer_feature_status_detail(signer_feature_status_t status) {
  switch (status) {
  case SIGNER_FEATURE_NOT_STARTED:
    return i18n_tr_or("feature.status.protected_detail",
                      "Sensitive paths are protected by default. Enter from an enabled wallet entry.");
  case SIGNER_FEATURE_UI_READY:
    return i18n_tr_or("feature.status.visible_detail",
                      "The entry and 4.3-inch layout are viewable.");
  case SIGNER_FEATURE_SERVICE_STUB:
    return i18n_tr_or("feature.status.maintenance_detail",
                      "This path needs dedicated maintenance and is hidden from the main menu by default.");
  case SIGNER_FEATURE_HARDWARE_WIRED:
    return i18n_tr_or("feature.status.available_detail",
                      "Can be used or checked from the corresponding page.");
  case SIGNER_FEATURE_VERIFIED:
    return i18n_tr_or("feature.status.checkable_detail",
                      "Basic checks are available in this version.");
  default:
    return i18n_tr_or("feature.status.unknown_detail", "Status unknown.");
  }
}

const char *signer_feature_risk_name(signer_feature_risk_t risk) {
  switch (risk) {
  case SIGNER_FEATURE_RISK_VIEW_ONLY:
    return i18n_tr_or("feature.risk.view_only", "View Only");
  case SIGNER_FEATURE_RISK_SECRET_MATERIAL:
    return i18n_tr_or("feature.risk.sensitive", "Sensitive");
  case SIGNER_FEATURE_RISK_SIGNING:
    return i18n_tr_or("feature.risk.signing", "Signing");
  case SIGNER_FEATURE_RISK_EXTERNAL_IO:
    return i18n_tr_or("feature.risk.peripheral", "Peripheral");
  case SIGNER_FEATURE_RISK_DEVICE_CONTROL:
    return i18n_tr_or("feature.risk.device", "Device");
  default:
    return i18n_tr_or("feature.risk.unknown", "Unknown");
  }
}

const char *signer_feature_risk_detail(signer_feature_risk_t risk) {
  switch (risk) {
  case SIGNER_FEATURE_RISK_VIEW_ONLY:
    return i18n_tr_or("feature.risk.view_only_detail",
                      "Shows only public information; risk is lower.");
  case SIGNER_FEATURE_RISK_SECRET_MATERIAL:
    return i18n_tr_or("feature.risk.sensitive_detail",
                      "Involves mnemonics, derived keys, or passwords; complete input, confirmation, backtracking, and memory cleanup are required.");
  case SIGNER_FEATURE_RISK_SIGNING:
    return i18n_tr_or("feature.risk.signing_detail",
                      "Involves transaction or message signing; full content review is required before enabling.");
  case SIGNER_FEATURE_RISK_EXTERNAL_IO:
    return i18n_tr_or("feature.risk.peripheral_detail",
                      "Involves camera, storage card, printer, or USB peripherals; hardware must be checked separately.");
  case SIGNER_FEATURE_RISK_DEVICE_CONTROL:
    return i18n_tr_or("feature.risk.device_detail",
                      "Involves clearing, locking, brightness, or maintenance operations; a second confirmation is required.");
  default:
    return i18n_tr_or("feature.risk.unknown_detail",
                      "Risk is unknown and is treated as high risk by default.");
  }
}

size_t signer_feature_count_by_status(signer_feature_status_t status) {
  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].status == status)
      count++;
  }
  return count;
}

size_t signer_feature_action_count(void) {
  size_t count = 0;
  for (size_t i = 0; i < signer_feature_count(); i++) {
    if (features[i].kind == SIGNER_FEATURE_ACTION)
      count++;
  }
  return count;
}
