#!/usr/bin/env python3
"""Generate the small multilingual UI fonts used by KernSigner.

LVGL's built-in fonts only cover a small Latin set. This script bakes the
glyphs used by the firmware UI and the bundled i18n table, plus printable
ASCII, so every supported language has visible glyphs without pulling whole
font files into firmware.
"""

import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "main/ui/assets"
SOURCE_GLOBS = ("main/**/*.c", "main/**/*.h")
GENERATED_FONT_PREFIX = "signer_cn_"
LATIN_FONT = Path("/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf")
ARABIC_FONT = Path("/usr/share/fonts/truetype/noto/NotoSansArabic-Regular.ttf")
DEVANAGARI_FONT = Path("/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf")
THAI_FONT = Path("/usr/share/fonts/truetype/noto/NotoSansThai-Regular.ttf")
CJK_TTC_FONT = Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc")
CJK_TTC_INDEX_SC = 2
CJK_FONT = REPO_ROOT / "build/font_cache/NotoSansCJKSC-Regular.ttf"
FONT_SIZES = (20, 28)
EXTRA_UI_SYMBOLS = (
    "：，。、；！？（）【】《》“”‘’·—"
    "固件会自动打开相机几秒钟串口日志记录是否收到画面导入钱包保存二维码内容"
)

# Keep most scripts to glyphs actually used by the firmware/i18n sources.
# Arabic/Persian is special: LVGL can reshape base Arabic characters into
# presentation-form codepoints at runtime, so bake those ranges proactively.
# Re-run this script after text changes; validate_font_coverage() catches misses.
SCRIPT_COVERAGE = (
    # Forms generated by LVGL's lv_text_ap.c Arabic/Persian shaper.
    (0xFB56, 0xFB59),
    (0xFB7A, 0xFB7D),
    (0xFB8A, 0xFB8B),
    (0xFB8E, 0xFB95),
    (0xFBFC, 0xFBFF),
    (0xFE81, 0xFE81),
    (0xFE83, 0xFEF5),
    (0xFEF7, 0xFEF7),
    (0xFEF9, 0xFEF9),
    (0xFEFB, 0xFEFB),
)


def range_symbols(start: int, end: int) -> str:
    return "".join(chr(cp) for cp in range(start, end + 1))


def collect_source_symbols() -> str:
    chars = set(EXTRA_UI_SYMBOLS)
    for pattern in SOURCE_GLOBS:
        for path in REPO_ROOT.glob(pattern):
            if path.parent == OUT_DIR and path.name.startswith(GENERATED_FONT_PREFIX):
                continue
            text = path.read_text(encoding="utf-8")
            chars.update(ch for ch in text if ord(ch) >= 0x80)
    return "".join(sorted(chars))


def collect_baked_symbols(required_symbols: str) -> str:
    chars = set(required_symbols)
    for start, end in SCRIPT_COVERAGE:
        chars.update(range_symbols(start, end))
    return "".join(sorted(chars))


def split_symbols(symbols: str) -> list[tuple[Path, str]]:
    latin = set()
    arabic = set()
    devanagari = set()
    thai = set()
    cjk = set()

    for ch in symbols:
        cp = ord(ch)
        if (
            0x0600 <= cp <= 0x06FF
            or 0x0750 <= cp <= 0x077F
            or 0x08A0 <= cp <= 0x08FF
            or 0xFB50 <= cp <= 0xFDFF
            or 0xFE70 <= cp <= 0xFEFF
        ):
            arabic.add(ch)
        elif 0x0900 <= cp <= 0x097F:
            devanagari.add(ch)
        elif 0x0E00 <= cp <= 0x0E7F:
            thai.add(ch)
        elif (
            0x2190 <= cp <= 0x22FF
            or 0x2500 <= cp <= 0x257F
            or 0x25A0 <= cp <= 0x25FF
            or 0x3000 <= cp <= 0x30FF
            or 0x4E00 <= cp <= 0x9FFF
            or 0xAC00 <= cp <= 0xD7AF
            or 0xFF00 <= cp <= 0xFFEF
        ):
            cjk.add(ch)
        else:
            latin.add(ch)

    return [
        (LATIN_FONT, "".join(sorted(latin))),
        (ARABIC_FONT, "".join(sorted(arabic))),
        (DEVANAGARI_FONT, "".join(sorted(devanagari))),
        (THAI_FONT, "".join(sorted(thai))),
        (CJK_FONT, "".join(sorted(cjk))),
    ]


def require_file(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"Missing font file: {path}")


def prepare_cjk_font() -> None:
    """Extract the SC face from Noto's TTC into a lv_font_conv-readable TTF."""
    require_file(CJK_TTC_FONT)
    if CJK_FONT.exists() and CJK_FONT.stat().st_mtime >= CJK_TTC_FONT.stat().st_mtime:
        return

    CJK_FONT.parent.mkdir(parents=True, exist_ok=True)
    code = f"""
from fontTools.ttLib import TTCollection
ttc = TTCollection({str(CJK_TTC_FONT)!r})
ttc.fonts[{CJK_TTC_INDEX_SC}].save({str(CJK_FONT)!r})
"""
    candidates = ["python3", "/tmp/kern_fonttools_venv/bin/python"]
    last_error = None
    for python in candidates:
        try:
            subprocess.run([python, "-c", code], check=True,
                           stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL)
            return
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            last_error = exc

    raise SystemExit(
        "fontTools is required to extract NotoSansCJK-Regular.ttc. "
        "Create a venv and install fonttools, then rerun this script. "
        f"Last error: {last_error}"
    )


def parse_int_list(body: str) -> list[int]:
    values = []
    for token in body.replace("\n", " ").split(","):
        token = token.strip()
        if not token:
            continue
        token = token.split("/*", 1)[0].strip()
        if not token:
            continue
        values.append(int(token, 0))
    return values


def parse_lvgl_font_codepoints(path: Path) -> set[int]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    lists: dict[str, list[int]] = {}
    import re

    for match in re.finditer(
        r"static const uint(?:8|16|32)_t (unicode_list_\d+)\[\] = \{(.*?)\};",
        text,
        re.S,
    ):
        lists[match.group(1)] = parse_int_list(match.group(2))

    codepoints: set[int] = set()
    cmap_block_match = re.search(r"static const lv_font_fmt_txt_cmap_t cmaps\[\].*?=\s*\{(.*?)\n\};", text, re.S)
    if not cmap_block_match:
        return codepoints
    for block in re.finditer(r"\{(.*?)\}", cmap_block_match.group(1), re.S):
        body = block.group(1)
        range_start = re.search(r"\.range_start\s*=\s*(\d+)", body)
        range_length = re.search(r"\.range_length\s*=\s*(\d+)", body)
        unicode_list = re.search(r"\.unicode_list\s*=\s*(NULL|unicode_list_\d+)", body)
        if not range_start or not range_length or not unicode_list:
            continue
        start = int(range_start.group(1))
        length = int(range_length.group(1))
        list_name = unicode_list.group(1)
        if list_name == "NULL":
            codepoints.update(range(start, start + length))
        else:
            codepoints.update(start + value for value in lists.get(list_name, []))
    return codepoints


def validate_font_coverage(output: Path, required_symbols: str) -> None:
    expected = {ord(ch) for ch in required_symbols}
    actual = parse_lvgl_font_codepoints(output)
    missing = sorted(expected - actual)
    if missing:
        preview = " ".join(f"U+{cp:04X}" for cp in missing[:40])
        raise SystemExit(
            f"{output.name} is missing {len(missing)} required glyphs: {preview}"
        )


def main() -> None:
    require_file(LATIN_FONT)
    require_file(ARABIC_FONT)
    require_file(DEVANAGARI_FONT)
    require_file(THAI_FONT)
    prepare_cjk_font()

    ascii_symbols = "".join(chr(cp) for cp in range(0x20, 0x7F))
    required_symbols = "".join(sorted(set(collect_source_symbols()) | set(ascii_symbols)))
    ui_symbols = "".join(sorted(set(collect_baked_symbols(required_symbols)) - set(ascii_symbols)))
    font_symbols = split_symbols(ui_symbols)

    for size in FONT_SIZES:
        output = OUT_DIR / f"signer_cn_{size}.c"
        font_args = []
        for font, symbols in font_symbols:
            if symbols:
                font_args.extend(["--font", str(font), "--symbols", symbols])
        subprocess.run(
            [
                "npx",
                "--yes",
                "lv_font_conv",
                "--size",
                str(size),
                "--bpp",
                "4",
                "--font",
                str(LATIN_FONT),
                "--symbols",
                ascii_symbols,
                *font_args,
                "--format",
                "lvgl",
                "--lv-include",
                "lvgl.h",
                "--lv-font-name",
                f"signer_cn_{size}",
                "-o",
                str(output),
                "--force-fast-kern-format",
                "--no-compress",
            ],
            check=True,
        )
        output.write_text(output.read_text(encoding="utf-8").rstrip() + "\n",
                          encoding="utf-8")
        validate_font_coverage(output, required_symbols)
        print(output)

    print(f"ASCII glyphs: {len(ascii_symbols)}")
    print(f"Required UI/i18n glyphs: {len(set(required_symbols) - set(ascii_symbols))}")
    print(f"Baked UI/script glyphs: {len(ui_symbols)}")
    for font, symbols in font_symbols:
        print(f"{font.name}: {len(symbols)} glyphs")


if __name__ == "__main__":
    main()
